services:
  ### MongoDB ###
  mongo:
    image: mongo:latest
    restart: always
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./init.js:/docker-entrypoint-initdb.d/init.js:ro
      - ./collections:/collections
#    networks:
#      - app-network
    environment:
      MONGO_INITDB_DATABASE: crimeLab
    command: ["--replSet", "rs0", "--bind_ip_all"]

  ### Neo4j ###
  neo4j:
    image: neo4j:latest
    restart: always
    environment:
      - NEO4J_AUTH=${NEO4J_AUTH}
    ports:
      - "7474:7474" # Port d'administration web
      - "7687:7687" # Port Bolt pour les connexions depuis une application
    container_name: neo4j
    volumes:
      - neo4j_data:/data
      - logs:/logs
#    networks:
#      - app-network

  ### Sync Service ###
  sync-service:
    depends_on:
      - mongo
      - neo4j
    build:
      context: ../sync-service
      dockerfile: Dockerfile
    env_file:
      - ../sync-service/.env
    container_name: sync-service
    ports:
      - "5001:5000"
#    networks:
#      - app-network

### Réseau pour connecter les services ###
#networks:
#  app-network:
#    driver: bridge

### Volumes persistants ###
volumes:
  mongo_data:
  logs:
  neo4j_data:
